### ISSUE TITLE
Horizontal centering does not work

### ISSUE THREAD

**Issue by krakxn** [DenverCoder1/readme-typing-svg#110]
## Description:

Horizontal centering (`center=true`) does not seem to work -- I have not tried committing the changes but in preview it does not get horizontally centered. Does the preview not show correctly or does it just not work?

Thank you!

## Code:

`[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Roboto&color=031C80&center=true&vCenter=false&width=400&height=50&lines=The+five+boxing+wizards+jump+quickly;How+vexingly+quick+daft+zebras+jump)](https://git.io/typing-svg)`

**Comment by DenverCoder1** [comment]
It looks correct to me.

The "horizontally centered" property center aligns the text *within the image*. You can see the effects more clearly by increasing the width parameter.

To center the image in a readme, you can use the align center HTML attribute, for example,

```html
<p align="center">
  <a href="https://github.com/DenverCoder1/readme-typing-svg"><img src="https://readme-typing-svg.herokuapp.com/?lines=Full-stack%20web%20and%20app%20developer;Experienced%20UI%2FUX%20Designer;10%2B%20years%20of%20coding%20experience;Always%20learning%20new%20things&font=Fira%20Code&center=true&width=440&height=45&color=f75c7e&vCenter=true&size=22"></a>
</p>
```

**Comment by krakxn** [comment]
Got it, closing this issue.

Also — made a PR.

Thank you!
