### ISSUE TITLE
Add ability to include a 'pause' at the end of a typed line before the next line begins

### ISSUE THREAD

**Issue by jsolly** [DenverCoder1/readme-typing-svg#118]
### is your feature request related to a problem? Please describe.
There currently isn't a way to pause the animation once it has finished typing. The motivation is that I want users to be able to read the typed sentence for a couple of seconds before the next line kicks off. I've gotten comments from nearly everyone who has reviewed my portfolio that they wish there was more time before the next line types.

The current implementation quickly goes to the next line after the current line has finished typing.

### Describe the solution you'd like
I would like the animation to stop at the end of the line for a specified time. After that time has passed, the next line begins.

### Describe alternatives you've considered
I tried adding lots of spaces at the end of the line, but that doesn't appear to lengthen the time the line is on screen.

The `duration` property isn't what I am looking for because that slows down the whole animation instead of adding a pause at the end of the line.

**Comment by DenverCoder1** [comment]
Note that the `duration` is the time it takes to draw the text path from the left to the right of the full image width.

One alternative option you have is to increase the **_`width`_** parameter to make extra space around the text. This empty space will be included in the duration and should allow you create a "pause".

A `pause` parameter with a duration may be a useful addition though as it would make it more intuitive and not require increasing the image size.

Let me know what you think

**Comment by jsolly** [comment]
Thanks for the reply! 

I do see that increasing the width does accomplish what I am looking for. The only issue is that the large length of the image is breaking my layout.

I want the SVG to be centered, so if I am increasing the image width, it pushes the svg off-center visually. Can you think of a way to keep the text centered while also increasing the width to achieve this 'pause'

**Comment by DenverCoder1** [comment]
Let me know what you think of the solution added in #119

**Comment by jsolly** [comment]
Beautifully implemented. I added the `pause` param right away. Check it out on my portfolio page! 🚀
https://blogthedata.com/category/portfolio/
