### ISSUE TITLE
Heroku alternative needed

### ISSUE THREAD

**Issue by manthanank** [DenverCoder1/readme-typing-svg#130]
**No free plans available in heroku**

A brief description of the question or issue: Since heroku is providing no free plans, heroku alternative needed.

**Comment by MagicLike** [comment]
What about Vercel & Docker?

**Comment by MagicLike** [comment]
@manthanank Is there a reason for closing?

**Comment by manthanank** [comment]
Not yet changed it's Backend heroku to vercel & docker as mentioned in above comment 🤔

**Comment by DenverCoder1** [comment]
I'll be keeping it on Heroku for the time being. Heroku will be sponsoring free credits for the project through the Open Source Program at least until February (and probably after as well once things are finalized by them).

Anyone who is interested in more info on Open Source credits should contact [ospo-heroku-credits@salesforce.com](mailto:ospo@salesforce.com).
