### ISSUE TITLE
Automate linting with prettier workflow

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/readme-typing-svg#147]
Add a Prettier workflow similar to the one in GitHub-readme-streak stats to format code or show lint errors on pull requests and push.

![image](https://user-images.githubusercontent.com/20955511/193474865-d2675995-3148-4ed4-85db-579189c07925.png)

Example code here (may require some changes): https://github.com/DenverCoder1/github-readme-streak-stats/pull/311/files

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by DenverCoder1** [comment]
@Vyvy-vi Sounds good :+1:
