### ISSUE TITLE
Font-weight support for Google Fonts

### ISSUE THREAD

**Issue by it-jhack** [DenverCoder1/readme-typing-svg#164]
#### Feature request
It would be nice to also be able to specify the font-weight

#### Idea
Add a new field below "Font size" on [https://readme-typing-svg.demolab.com/demo/](https://readme-typing-svg.demolab.com/demo/) to be able to specify font-weight, as there are many different options in Google Fonts.

**Comment by it-jhack** [comment]
Hi @DenverCoder1 I just opened a [Pull Request](https://github.com/DenverCoder1/readme-typing-svg/pull/165) for this feature _(my first open-source PR ever, yaaay :partying_face: )_. I'd appreciate it very much if you can take a look into it. I'm looking forward for a review :smile:  Please let me know if I missed something. Thanks!

**Comment by DenverCoder1** [comment]
Awesome! I'm looking at it now. :+1:
