### ISSUE TITLE
Option not to erase/rewrite text

### ISSUE THREAD

**Issue by seisvelas** [DenverCoder1/readme-typing-svg#19]
**Is your feature request related to a problem? Please describe.**

Currently, once the text is written, it's then erased and rewritten over and over. 

**Describe the solution you'd like**

I'd love an option for it to write the text once and for the text to just stay written. 

**Additional context**

This is so cool, thanks for making this!

**Comment by DenverCoder1** [comment]
Interesting idea :+1: Shouldn't be too hard to add.

To clarify, how would this work if multiple lines are specified?

**Comment by seisvelas** [comment]
>To clarify, how would this work if multiple lines are specified?

Hmmm. Okay, this would be my ideal scenario:

They could appear on newlines, one after the other. Not sure how hard it would be to implement that way, though.

**Comment by DenverCoder1** [comment]
Hi, I can get started on this if you'd like. It may take a few hours to get it working.

**Comment by seisvelas** [comment]
Awesome, thanks! You are the best!

**Comment by DenverCoder1** [comment]
@seisvelas How does this look (the GIF is a bit sped up)

![multiline](https://user-images.githubusercontent.com/20955511/116604088-5ee00580-a936-11eb-8498-2f3c7686e01f.gif)

**Comment by seisvelas** [comment]
Nice, that looks wonderful!

**Comment by seisvelas** [comment]
You truly are a magician

**Comment by DenverCoder1** [comment]
[It's merged!](https://readme-typing-svg.herokuapp.com/?multiline=true&color=%232F2F2FD2&size=17&width=720&height=200&lines=Initializing+memory...+bootloading+XANDRE+image+from+Unix+cache...;guest%40GH+~%2Fwelcome+%24+whoami;GUEST+SESSION+++webtty++UNIX+V5;guest%40GH+~%2Fwelcome+%24+ls+-la;.htpasswd+++secrets.env+++README+++btc_private_key;guest%40GH+~%2Fwelcome+%24+cat+README;WUT%5EM%5EM%5EM+Hey!+I%27m+Xandre.+I+hack+computers.;guest%40GH+~%2Fwelcome+%24+init+6+%23+reboot+%3A3;REBOOT+IN+5....+4.....+3.....+2.....+1.....+NOW.) :tada:
