### ISSUE TITLE
Add a background color parameter

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/readme-typing-svg#2]
Allow changing the background color of the SVG with a URL parameter.

**Comment by Evavic44** [comment]
> Allow changing the background color of the SVG with a URL parameter.

Is it a single color? What color do you prefer?

**Comment by DenverCoder1** [comment]
@Evavic44 It should be a URL parameter, like `background=435F6A`.

Like what we have for font color, but to allow the user to customize the background color.

**Comment by Evavic44** [comment]
> @Evavic44 It should be a URL parameter, like `background=435F6A`.
> 
> Like what we have for font color, but to allow the user to customize the background color.

Something like this? 

```css
  .text {
     background-color: #435F6A
  }
```

**Comment by DenverCoder1** [comment]
@Evavic44 Using CSS could work. I was originally thinking to make a rectangle in the background and color it, but adding a `background-color` to the `<svg>` element should work as well.

I think it could even be done inline like this:

```diff
<svg xmlns='http://www.w3.org/2000/svg'
    xmlns:xlink='http://www.w3.org/1999/xlink'
    viewBox='0 0 <?php echo "$width $height" ?>'
+   style="background-color: <?php echo $background ?>;"
    width='<?php echo $width ?>px' height='<?php echo $height ?>px'>
```

The $background variable will also need to be added in the RendererView and RendererModel, and validated in the model as well.
