### ISSUE TITLE
Trailing ";" in line parameter causes empty line to be animated

### ISSUE THREAD

**Issue by 8BitJonny** [DenverCoder1/readme-typing-svg#25]
**Describe the bug**

**To Reproduce**
Actually I can show you the bug in here
First I'll show you how `![](https://readme-typing-svg.herokuapp.com/?lines=First+line;Second+line)` looks:
![](https://readme-typing-svg.herokuapp.com/?lines=First+line;Second+line)
Normal right? Yes.

Now `![](https://readme-typing-svg.herokuapp.com/?lines=First+line;Second+line;)` (notice the trailing ";" in the line query param:
![](https://readme-typing-svg.herokuapp.com/?lines=First+line;Second+line;)

Watch how first "First line" appears, then "Second line" appears and then a big pause before it starts a new?
The issue is obviously the trailing ";" that creates an empty line at the very end to be animated.

**Expected behavior**
I think that's debatable but I would argue, since it is not hard to remove a trailing ";" the expected result is no big pause before it repeats itself, EVEN IF the url contains an accidental trailing ";"

This bug is tiny but imo it would be a slight improvement to user friendliness when fixed. Let me know, your opinion on this topic.
If you agree, I would be open to fixing this issue myself, in order to play a little with php (I the web I only worked with js for the last 4 years, no php, no jquery)

**Comment by DenverCoder1** [comment]
That would be great if you can fix it!

If you have any questions, don't hesitate to ask! :smile:
