### ISSUE TITLE
How to center align the readme-typing

### ISSUE THREAD

**Issue by Hammad1007** [DenverCoder1/readme-typing-svg#275]
**Description**

A brief description of the question or issue:
Hi, so I am facing a little issue while implementing the code. The issue is that when I paste the following code in my readme.md file, I am unable to center align the sentences. Although I have set the variable center to true, but still it gives an issue. Can you guide me how can I resolve this bug
```
[![Typing SVG](https://readme-typing-svg.demolab.com?font=fira+code&pause=1000&center=true&random=false&width=435&lines=Computer+Science;Software+Quality+Assurance+Engineer)](https://git.io/typing-svg)

```

**Comment by DenverCoder1** [comment]
The text is centered within the image by using the `center` parameter.

If you want to center it on the page in the readme, you'll need to use the HTML syntax instead with the align attribute set to center:

```html
<p align="center">
  <a href="https://git.io/typing-svg"><img src="https://readme-typing-svg.demolab.com/?font=fira+code&pause=1000&center=true&random=false&width=435&lines=Computer+Science;Software+Quality+Assurance+Engineer"/></a>
</p>
```

More info in the FAQ: https://github.com/DenverCoder1/readme-typing-svg/blob/main/docs/faq.md#how-do-i-center-the-image-on-the-page

**Comment by Hammad1007** [comment]
Thanks a lot. I'll surely look into this 👍🏻

**Comment by Hammad1007** [comment]
Thanks a lot. Your solution helped me alot
