### ISSUE TITLE
Use inherited colors for svg text

### ISSUE THREAD

**Issue by jahirfiquitiva** [DenverCoder1/readme-typing-svg#283]
**Is your feature request related to a problem? Please describe.**

Since we can have/use light and dark themes, the generated SVG colors might not always have a color with enough contrast.

**Describe the solution you'd like**

Make the SVG use the inherited color by default (i.e. if no specific color is set in the URL).
This can be done with css and the `inherit` or `currentColor` properties.

**Comment by DenverCoder1** [comment]
That doesn't work when the svg is used through an img tag, styling features do not get applied.

You can use special markup to make different versions for dark mode and light mode, though - https://github.com/DenverCoder1/readme-typing-svg/blob/main/docs/faq.md#how-do-i-make-different-svgs-for-dark-mode-and-light-mode

**Comment by jahirfiquitiva** [comment]
thanks for the suggestion @DenverCoder1 😀🙌
