### ISSUE TITLE
Animated text not correctly displaying

### ISSUE THREAD

**Issue by 8BitJonny** [DenverCoder1/readme-typing-svg#29]
### **Describe the bug**
The given lines are `lines=Type+messages+everywhere!;Add+a+bio+to+your+profile!;Add+a+description+to+your+repo!;Make+your+readme+stand+out!` and yet the third line is animated as `dd+a+description+to+your+repo!` with the missing A

Have a look at the Readme of this Repo: https://github.com/DenverCoder1/readme-typing-svg
or see it directly by visiting the link that I posted below, or the gif and the end of this bug report.

### **To Reproduce**
Visit https://readme-typing-svg.herokuapp.com/?lines=Type+messages+everywhere!;Add+a+bio+to+your+profile!;Add+a+description+to+your+repo!;Make+your+readme+stand+out!&center=true&width=360&height=50%22 which is exactly the link that is currently on top of this repo's readme

### **Expected behavior**
The third line should not be missing the `A` at the start

### **Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32591853/116814594-0e48f200-ab5a-11eb-94d0-f2bd528091e0.gif)

**Comment by 8BitJonny** [comment]
I first saw that issue a couple of days ago. So it was not introduced by #28 or #26

**Comment by 8BitJonny** [comment]
Currently no idea why that is happening

**Comment by DenverCoder1** [comment]
It displays correctly for me.

It must be that the text is too wide with the font you have for monospace.

We could possibly fix this by using a font from Google Fonts instead of the default.

**Comment by 8BitJonny** [comment]
Interesting 🤔 
You're completely right. Sorry for not noticing but yes, the content is simply to long for the width. I looked it up and it renders as 20px Courier on my Mac.

I think as a low priority bug this could be actually a nice one to fix. By defining a google font as a default we eliminate this "uncertainty" of which font the user's machine selects at the end to display this text. And this Ticket shows, that there are cases where the content is not correctly rendered.

Let's leave this ticket open for now. I have a full schedule for the next days, but if this ticket is still open in a week or two, I can create the fix. The only thing that is left to be decided, is which google font to use as a default. As you are the owner of this repo (and since I don't really have much of an educated opinion with fonts) I'll let you choose that

Thanks for the quick response

**Comment by DenverCoder1** [comment]
There are lots of good options. I think a Monospace font is best since it's more code-like.

https://fonts.google.com/?category=Monospace

Maybe we could do Fira Code?

https://fonts.google.com/specimen/Fira+Code

**Comment by 8BitJonny** [comment]
Fira Code looks good. I also like Courier Prime. And Jetbrains Mono is a third good option since all [JetBrains IDE's](https://www.jetbrains.com/products/#type=ide) use it as a default so lots of people will already be familiar with this font

Here you can compare all three
https://fonts.google.com/share?selection.family=Courier%20Prime%7CFira%20Mono%7CJetBrains%20Mono

**Comment by DenverCoder1** [comment]
All of those look good. Any of those could be used.

**Comment by adityaraute** [comment]
Any progress on this front?

**Comment by 8BitJonny** [comment]
I'm currently swamped with work and it'll probably stay like that for another 2 weeks.
So I'm not able to work on it but everybody else is invited to 👍🏼

**Comment by DenverCoder1** [comment]
Any updates?

This should be a quick fix as it seems like we just need to add the font parameter and adjust the width until it's large enough.

If you're available, it would be great to have you contribute! :smile:

**Comment by 8BitJonny** [comment]
In a few hours I have the first out of two final assessments for my university degree.
So give me another few days, ok 😅

**Comment by DenverCoder1** [comment]
Of course, no problem. There's no rush.

**Comment by DenverCoder1** [comment]
@8BitJonny Any updates?
