### ISSUE TITLE
It’s not syncing fonts colours dynamically with device theme

### ISSUE THREAD

**Issue by iamharshtrivedi** [DenverCoder1/readme-typing-svg#335]
**Describe the bug**
Font colour is not syncing with device theme. 

**Expected behavior**
It’s should be dynamic like Black Font for Light theme and White Font for Dark Theme.

**Comment by DenverCoder1** [comment]
It's an image, so it can't do it automatically, but there are instructions in the faq

https://github.com/DenverCoder1/readme-typing-svg/blob/main/docs%2Ffaq.md
