### ISSUE TITLE
Improve contrast of links in dark mode

### ISSUE THREAD

**Issue by schmelto** [DenverCoder1/readme-typing-svg#55]
![image](https://user-images.githubusercontent.com/30869493/135641913-b4046f09-addf-443b-9807-3354859eb847.png)

Improcing contrast for links in dark mode for the website.

**Comment by schmelto** [comment]
Could you assign me to this?

**Comment by DenverCoder1** [comment]
For me it appears like this, but I suppose those pictures are from the 0.5s before it loads?

![image](https://user-images.githubusercontent.com/20955511/135644735-c0bac8a7-d0fd-48cc-addd-61b7de58a781.png)

If you'd like to fix it, that would be great!

**Comment by schmelto** [comment]
for me its looking like this:
![image](https://user-images.githubusercontent.com/30869493/135646710-769103df-9183-48fe-b4ab-a9a3e8931b93.png)

**Comment by DenverCoder1** [comment]
It is using https://github.com/ntkme/github-buttons, so it shouldn't display like that, unless the script is blocked for you or something.

**Comment by schmelto** [comment]
this could be ..

**Comment by schmelto** [comment]
I thinks as its only a skript problem from my side we could close this issue

**Comment by DenverCoder1** [comment]
I assume it displays correctly for most users.

It's still a valid issue since it's possible for some users it won't display (as it did for you).

If you'd like to make the fallback look nicer, you can feel free to, but if you don't think it's worth the effort, you can just close it.

**Comment by schmelto** [comment]
I leave it open but someone else can work on this issue :)
