### ISSUE TITLE
Return proper HTTP response codes for errors

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/readme-typing-svg#59]
Currently all responses return 200 (unless there is a server error, in which case 500).

It would be best to have specific codes for different types of errors to differentiate between them.

Example:

400 - Bad request

etc.

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by DenverCoder1** [comment]
@Vyvy-vi Go for it :+1:

**Comment by mpa12** [comment]
@DenverCoder1 Do you need constants to determine HTTP statuses?

The only place where I found a comparison of HTTP status: GoogleFontConverter->curlGetContents

```php
    /**
     * Get the contents of a URL
     *
     * @param string $url The URL to fetch
     * @return string Response from URL
     */
    private static function curlGetContents($url): string
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_AUTOREFERER, true);
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_VERBOSE, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        //! THERE
        if ($httpCode != 200) {
            throw new InvalidArgumentException("Failed to fetch Google Font from API.");
        }
        return $response;
    }
```

**Comment by DenverCoder1** [comment]
There are many ways it could be implemented, constants could help with readability so that sounds good to me

It will not be the same implementation of course, but here is a PR for a similar issue in another project https://github.com/DenverCoder1/github-readme-streak-stats/pull/192

**Comment by mpa12** [comment]
Enums were added in PHP 8.1. I can update the PHP version to 8.1 and use them to solve this problem

> There are many ways it could be implemented, constants could help with readability so that sounds good to me
> 
> It will not be the same implementation of course, but here is a PR for a similar issue in another project [DenverCoder1/github-readme-streak-stats#192](https://github.com/DenverCoder1/github-readme-streak-stats/pull/192)
