### ISSUE TITLE
Improve Contribution guidelines

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [DenverCoder1/readme-typing-svg#66]
The `CONTRIBUTING.md` file doesn't mentions the steps how to contribute (Clone, Fork, Create a Branch etc etc).
It mentions the project's local installation and setup but doesn't mentions the instructions of how to contribute.

I wish to add a detailed workflow of the steps to contribute.
It will help the beginners, reduce the chances of errors, enhance the documentation and help to manage the open-source project more efficiently.

**Comment by DenverCoder1** [comment]
Sounds great.

Since the issue text is the same, I assume you intend to add something similar to the [CONTRIBUTING.md of  Streak Stats](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/CONTRIBUTING.md#submitting-contributions-). That would be a nice addition. :+1:
