### ISSUE TITLE
Delay in new line when `Horizontally Centered` is true

### ISSUE THREAD

**Issue by PROxZIMA** [DenverCoder1/readme-typing-svg#68]
**Describe the bug**
There is a noticeable delay in new lines when `Horizontally Centered` is set to `true` AND width of the line is less than width of the `svg`

**To Reproduce**
1. Go to https://readme-typing-svg.herokuapp.com/demo/
2. Add lines `There is no problem in this line as it is long.`, `But this takes`, `time to appear :(`
3. Set `Horizontally Centered` to `true`

**Expected behavior**
No delay in occurrence of new line is expected

**Screenshots**

https://user-images.githubusercontent.com/43103163/138579361-baf148ea-077a-4ded-8004-efe9c4fb42d3.mp4

**Desktop (please complete the following information):**
 - OS: Linux(Pop!_OS)
 - Browser: Firefox
 - Version: v93

**Comment by DenverCoder1** [comment]
The issue is that it is difficult to find out the `textWidth` since you can only really know exactly how long it will be after it is rendered.
