### ISSUE TITLE
Potential XSS vulnerability

### ISSUE THREAD

**Issue by plamoni** [DenverCoder1/readme-typing-svg#7]
**Describe the bug**
XSS vulnerability via the “lines” argument.

**To Reproduce**
1. Go to https://readme-typing-svg.herokuapp.com/?lines=First+line+of+text;Second+line+of+%3C/textPath%3E%3C/text%3E%3Cscript%3Ealert(%22xss?%22)%3C/script%3E%3Ctext%3E%3CtextPath%3E

**Expected behavior**
Image should fail to load or load without an alert box.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Tested in iOS and Win10
 - Browser: Chrome
 - Version: 87/88

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.4.2
 - Browser: Chrome
 - Version: 87

**Additional context**
As discussed on discord, this is probably a minimal issue due to other protections. But if someone incorporates the code as a library, then they could be at risk.

**Comment by DenverCoder1** [comment]
Using `htmlspecialchars()` to escape the the lines seems to be a sufficient fix.

I'll just need to double check that there's nothing in SVGs that needs to be treated separately.

[Example SVG with new code](https://freshidea.com/jonah/app/typing-svg/xss-fixed.svg)

**Comment by DenverCoder1** [comment]
Thanks for your help @plamoni!

With #8, I think it should be safe now.
