### ISSUE TITLE
Spaces in new lines not working

### ISSUE THREAD

**Issue by brettcurtis** [DenverCoder1/readme-typing-svg#74]
**Describe the bug**
Spaces in new line don't appear to be working. I tried with +++ and %20, no go.

**To Reproduce**
```code
[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=roboto&color=%234B5862&vCenter=true&multiline=true&width=600&height=125&lines=resource+%22infrastructure_as_code%22+%22developer%22+%7B;+++name+%3D+%22My+Name%22;+++location+%3D+%22Maine%22;%7D)](https://git.io/typing-svg)
```

**Expected behavior**
Line 2 and 3 indented three spaces.

**Comment by DenverCoder1** [comment]
I suppose that's expected since xml/svg ignores treats multiple spaces as just one (same with html).

A workaround could be to use other whitespace characters (for example, you can copy-paste the en-space from https://qwerty.dev/whitespace/)

The alternate whitespace characters don't get ignored.

**Comment by brettcurtis** [comment]
Perfecto, Thanks!!
