### ISSUE TITLE
Google Font Error

### ISSUE THREAD

**Issue by VikashPR** [DenverCoder1/readme-typing-svg#87]
**Describe the bug**

I tried to deploy the app in my Heroku account. It works fine but when every I change new font I'am getting some error in the output.
**To Reproduce**
1. Go to [My deployed domain](https://typing-text-svg.herokuapp.com/demo/)
2. Change the font to QuickSand or any other font.

**Expected behavior**

I wanted my deployment link to work like the original one

**Screenshots**
![Screenshot 2022-02-28 at 7 50 57 AM](https://user-images.githubusercontent.com/69889418/155913605-ef20f683-8dbd-450a-a9ab-cc17d0ddd547.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari
 - Version 12.2.1
 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenverCoder1** [comment]
A table also needs to be created in the database called `fonts` with fields `fetch_date` and `css`

**Comment by VikashPR** [comment]
oh alright, TBH I have no prior experience with Heroku before and Postgres. I tried to enable dynos but I was not able get it working. 
Is there any other way ?
or can you please help me out to get it working ?

**Comment by DenverCoder1** [comment]
Here is the definition for the table:

```sql
CREATE TABLE fonts (
	"family" varchar(50) NOT NULL,
	css varchar(1200000) NOT NULL,
	fetch_date date NOT NULL,
	CONSTRAINT fonts_pkey PRIMARY KEY (family)
);
```

You'll need to use the database credentials (found by clicking the Postgres add-on and going to Settings) to add this table to your database.

![image](https://user-images.githubusercontent.com/20955511/156227168-010b11bb-e94e-40a1-9f70-a3ea83dd3427.png)

You can do it from a postgreSQL command line tool or connect through a GUI such as DBeaver or others. You can probably find a tutorial that can give you steps for that.

You can add the fields manually in a GUI or use a CLI or SQL editor in a GUI and run the snippet I posted above.

**Comment by DenverCoder1** [comment]
The latest version of the code no longer uses the postgresql database, so if you want to try it now, it shouldn't have this issue
